'use client';

import { useEffect, useState, useCallback } from 'react';
import { Newspaper, RefreshCw } from 'lucide-react';

export function SmartDigest() {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  const fetchDigest = useCallback(async () => {
    try {
      setLoading(true);
      const res = await fetch('/api/smart-digest');
      const json = await res.json();
      setSummary(json.summary ?? null);
      setGeneratedAt(json.generatedAt ?? null);
    } catch {
      setSummary('Unable to reach the Gemini digest service. Ethiopia indicators and map layers are still updating in real time.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchDigest(); }, [fetchDigest]);

  return (
    <footer
      className="h-16 border-t border-radar-border backdrop-blur-xl flex items-center shrink-0 z-30"
      style={{ background: 'var(--radar-panel)' }}
    >
      {/* Label */}
      <div className="w-44 border-r border-radar-border h-full flex items-center px-4 shrink-0 gap-2">
        <Newspaper className="text-radar-accent w-4 h-4 shrink-0" />
        <div>
          <p className="text-[10px] font-black uppercase tracking-widest leading-none" style={{ color: 'var(--foreground)' }}>
            Smart Digest
          </p>
          <p className="text-[8px] uppercase tracking-wider opacity-40 mt-0.5" style={{ color: 'var(--foreground)' }}>
            Gemini · Ethiopia
          </p>
        </div>
      </div>

      {/* Summary text */}
      <div className="flex-1 px-5 overflow-hidden">
        <p
          className="text-[12px] leading-snug italic truncate"
          style={{ color: 'var(--foreground)', opacity: loading && !summary ? 0.4 : 0.85 }}
        >
          {loading && !summary
            ? 'Generating Ethiopia-focused brief from latest indicators...'
            : summary || 'Awaiting event data. Gemini will synthesise an Ethiopia briefing once signals accumulate.'}
        </p>
        {generatedAt && (
          <p className="text-[8px] font-mono uppercase tracking-widest opacity-30 mt-0.5" style={{ color: 'var(--foreground)' }}>
            Updated {new Date(generatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            {' · '}Generated by Gemini AI
          </p>
        )}
      </div>

      {/* Refresh */}
      <div className="px-5 shrink-0">
        <button
          type="button"
          onClick={fetchDigest}
          disabled={loading}
          className="flex items-center gap-1.5 text-[9px] font-mono uppercase tracking-widest text-radar-red hover:opacity-80 transition-opacity disabled:opacity-40"
          aria-label="Refresh Ethiopia Gemini digest"
        >
          <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
          {loading ? 'Refreshing…' : 'Refresh'}
        </button>
      </div>
    </footer>
  );
}
